"""Fallback behavioral question builder (used when OpenAI is unavailable)."""

from typing import List

from app.schemas.guide import GeneratedQuestion, GenerateQuestionsRequest


_QUESTIONS: dict = {
    "it": {
        "en": {
            "logic": [
                "When my code produces an unexpected result, I add print statements or use a debugger to trace exactly where values change.",
                "Before writing a function, I write down the expected inputs, outputs, and edge cases on paper first.",
                "When I encounter a bug I have seen before, I check whether the fix I used last time still applies to this new context.",
                "I break a large programming task into the smallest independent pieces before I start writing any code.",
                "When two approaches solve the same problem, I compare their trade-offs in memory, speed, and readability before choosing one.",
            ],
            "data": [
                "Before choosing a database structure, I estimate how many records might grow over the next two years.",
                "I read error logs and stack traces carefully before searching for a solution online.",
                "When a system is slow, I measure which part takes the most time before attempting any optimisation.",
                "I look at real usage statistics before deciding which feature to improve next.",
                "When reviewing code, I check whether edge-case inputs (empty list, zero, null) are handled correctly.",
            ],
            "creativity": [
                "When I cannot solve a problem with a familiar pattern, I try at least two completely different approaches before asking for help.",
                "I enjoy building small experimental projects to test an idea before committing to a full implementation.",
                "When I learn a new tool or library, I go beyond the tutorial and try to solve a problem it was not designed for.",
                "I look for open-source projects related to my problem to see how others have approached it, then adapt ideas to my context.",
                "When a feature request seems hard to implement, I think about whether a simpler version would still meet the core need.",
            ],
            "people": [
                "When reviewing code written by a teammate, I comment on what works well before suggesting what could be clearer.",
                "When I do not understand a requirement, I ask one specific clarifying question rather than making an assumption.",
                "I write commit messages and pull-request descriptions so that a teammate can understand the change without asking me.",
                "When a user reports a bug, I ask them to describe the steps they took rather than immediately guessing the cause.",
                "I share what I learned from a failed experiment so my team does not repeat the same mistake.",
            ],
            "technical": [
                "I can set up a working development environment from a README without needing step-by-step assistance.",
                "I use version control for every project I work on, including personal side projects.",
                "When I deploy an application, I verify it works in the target environment before marking the task as done.",
                "I write at least one automated test for every function I add to a shared codebase.",
                "I keep dependencies up to date and check release notes before upgrading a major library.",
            ],
        },
        "ru": {
            "logic": [
                "Когда мой код выдаёт неожиданный результат, я добавляю print или использую отладчик, чтобы отследить, где именно меняются значения.",
                "Перед написанием функции я записываю ожидаемые входные данные, результат и крайние случаи.",
                "Когда я встречаю знакомую ошибку, я проверяю, применим ли прежний способ исправления к новому контексту.",
                "Большую задачу по программированию я разбиваю на наименьшие независимые части перед тем, как начать писать код.",
                "Когда два подхода решают одну задачу, я сравниваю их компромиссы по памяти, скорости и читаемости.",
            ],
            "data": [
                "Перед выбором структуры базы данных я оцениваю, сколько записей может появиться за два года.",
                "Я внимательно читаю логи ошибок и трассировки стека до того, как искать решение в интернете.",
                "Когда система работает медленно, я измеряю, какая часть занимает больше всего времени.",
                "Я смотрю на статистику использования, прежде чем решать, какую функцию улучшать следующей.",
                "При проверке кода я убеждаюсь, что крайние случаи (пустой список, ноль, null) обрабатываются правильно.",
            ],
            "creativity": [
                "Когда знакомый шаблон не решает задачу, я пробую хотя бы два принципиально разных подхода.",
                "Мне нравится строить небольшие экспериментальные проекты, чтобы проверить идею до полноценной реализации.",
                "Изучая новый инструмент, я выхожу за рамки туториала и пробую решить задачу, для которой он не предназначен.",
                "Я изучаю open-source проекты по теме, чтобы понять, как другие решали похожие задачи.",
                "Когда функция кажется сложной в реализации, я думаю, сможет ли более простая версия закрыть основную потребность.",
            ],
            "people": [
                "Проверяя код коллеги, я сначала указываю, что работает хорошо, а затем предлагаю улучшения.",
                "Когда требование непонятно, я задаю один конкретный уточняющий вопрос, а не строю предположения.",
                "Я пишу сообщения к коммитам так, чтобы коллега мог понять изменение без вопросов ко мне.",
                "Когда пользователь сообщает об ошибке, я прошу его описать шаги, а не сразу угадываю причину.",
                "Я делюсь выводами из провального эксперимента, чтобы команда не повторяла ту же ошибку.",
            ],
            "technical": [
                "Я могу настроить рабочую среду разработки по README без пошаговой помощи.",
                "Я использую систему контроля версий для каждого проекта, включая личные.",
                "Перед тем как считать задачу выполненной, я проверяю работу приложения в целевой среде.",
                "Я пишу хотя бы один автоматический тест для каждой новой функции в общем коде.",
                "Я обновляю зависимости своевременно и изучаю примечания к выпуску перед обновлением.",
            ],
        },
        "uz": {
            "logic": [
                "Kodum kutilmagan natija bersa, qiymatlar qayerda o'zgarayotganini aniqlaш uchun print yoki debugger ishlataman.",
                "Funksiya yozishdan oldin kutilgan kiruvchi ma'lumotlar, natija va chegaraviy holatlarni qog'ozga yozaman.",
                "Tanish xatoga duch kelganimda, avvalgi yechim yangi kontekstda ham ishlashini tekshiraman.",
                "Katta dasturlash vazifasini kod yozishni boshlashdan oldin eng kichik mustaqil qismlarga ajrataman.",
                "Ikki yondashuv bir muammoni hal qilsa, birini tanlashdan oldin xotira, tezlik va o'qilishini solishtiram.",
            ],
            "data": [
                "Ma'lumotlar bazasi strukturasini tanlashdan oldin ikki yil ichida nechta yozuv ko'payishi mumkinligini baholаyman.",
                "Internetda yechim izlashdan oldin xato loglarini va stack trace'ni diqqat bilan o'qiyman.",
                "Tizim sekin ishlasa, optimallashtirish urinishidan oldin qaysi qism ko'p vaqt olayotganini o'lchayman.",
                "Qaysi funksiyani keyingi takomillashtirish kerakligini hal qilishdan oldin real foydalanish statistikasiga qarayman.",
                "Kodni tekshirayotganda, chegaraviy kirishlar (bo'sh ro'yxat, nol, null) to'g'ri ishlanganini aniqlayman.",
            ],
            "creativity": [
                "Tanish shablon muammoni hal qilmasa, yordam so'rashdan oldin kamida ikkita butunlay boshqacha yondashuv sinab ko'raman.",
                "To'liq amalga oshirishga o'tishdan oldin g'oyani sinash uchun kichik eksperimental loyiha yaratishni yoqtiraman.",
                "Yangi asbob o'rganayotganimda, darslikdan tashqariga chiqib uni mo'ljallanmagan muammo uchun ishlatishga urinaman.",
                "Muammo bo'yicha open-source loyihalarni ko'rib, boshqalar qanday yechim topganini o'rganaman va g'oyalarni moslashtiraman.",
                "Funksiya qiyin ko'rinsa, asosiy ehtiyojni oddiyroq versiya qoplay oladimi deb o'ylayman.",
            ],
            "people": [
                "Jamoachi kodini tekshirayotganda, avval nimasi yaxshi ekanligini aytib, keyin nima aniqlashtirish mumkinligini tavsiya qilaman.",
                "Talab tushunarsiz bo'lsa, taxmin qilish o'rniga bitta aniq savolni beraman.",
                "Commit xabarlarini shunday yozamanki, jamoachi o'zgarishni menga savol bermasdan tushuna olsin.",
                "Foydalanuvchi xabar bersa, darhol sabab taxmin qilmasdan, u amalga oshirgan qadamlarni ta'riflab berishini so'rayman.",
                "Muvaffaqiyatsiz tajribadan chiqargan xulosalarni ulashaman, jamoa bir xil xatoni takrorlamasin.",
            ],
            "technical": [
                "README bo'yicha bosqichma-bosqich yordamsiz ish muhitini sozlay olaman.",
                "Shaxsiy loyihalar jumladan har bir loyiha uchun versiya nazorat tizimidan foydalanaman.",
                "Ilovani joylashtirganда, vazifani bajarilgan deb belgilashdan oldin maqsadli muhitda ishlashini tekshiraman.",
                "Umumiy kodga qo'shgan har bir funksiya uchun kamida bitta avtomatlashtirilgan test yozaman.",
                "Bog'liqliklarni vaqtida yangilab, asosiy kutubxonani yangilashdan oldin chiqarilish eslatmalarini o'qiyman.",
            ],
        },
    },
    "design": {
        "en": {
            "logic": [
                "When a user cannot complete a task in my design, I trace through the step-by-step flow to find exactly where they get stuck before changing any visuals.",
                "Before starting a new screen layout, I write down the user's goal and the three most likely paths they might take.",
                "When I receive conflicting feedback from two stakeholders, I map each piece of feedback to a specific user need before deciding which to prioritise.",
                "I create a clear visual hierarchy in every design so a first-time user knows where to look first without any instructions.",
                "When a design change is requested, I check whether it creates a consistency problem with other screens before implementing it.",
            ],
            "data": [
                "I look at user behaviour data — click maps or session recordings — to find which parts of an interface people avoid before redesigning them.",
                "After launching a design update, I check key metrics (task completion rate, drop-off) to see whether the change had the expected effect.",
                "When I have two layout options, I define a measurable success criterion before running a test.",
                "I track how long users take to complete a task, not just whether they succeed.",
                "Before a usability test, I write down what specific behaviour would count as success and what would count as failure.",
            ],
            "creativity": [
                "I generate at least three to five rough layout concepts before selecting one to develop in detail.",
                "When a standard UI pattern does not serve a specific user need, I propose and test a custom solution.",
                "I use mood boards or reference collections to explore visual directions before committing to a style.",
                "I push myself to include at least one unconventional idea in every brainstorm session.",
                "When I am stuck on a visual problem, I sketch ten variations in ten minutes to break through the block.",
            ],
            "people": [
                "I conduct at least one user interview to discover real problems before starting a new design.",
                "When a developer says my design is too complex to build, I ask them to show me the specific constraint so we can adjust together.",
                "I present designs with the user's goal at the top — not the feature name — so stakeholders focus on the right outcome.",
                "I ask users to think aloud while completing a task so I can hear their reasoning, not just observe their clicks.",
                "When a design decision is based on a user insight, I document the insight so the team can reference it later.",
            ],
            "technical": [
                "I can build an interactive prototype in Figma that demonstrates at least five different screen transitions.",
                "Before handing off to a developer, I check that all components are consistent and named following the design system.",
                "I set up auto-layout in my design files so that components resize correctly across different screen widths.",
                "I understand the difference between vector and raster formats and choose the correct export setting for each asset.",
                "When a developer asks whether a design is possible to build, I can discuss technical constraints and propose an alternative.",
            ],
        },
        "ru": {
            "logic": [
                "Когда пользователь не может выполнить задачу в моём дизайне, я прохожу по шагам потока, чтобы найти точку затруднения до изменения визуала.",
                "Перед созданием нового экрана я записываю цель пользователя и три наиболее вероятных пути.",
                "Получая противоречивые отзывы, я соотношу каждый из них с конкретной потребностью пользователя.",
                "В каждом дизайне я создаю чёткую визуальную иерархию, чтобы новый пользователь знал, куда смотреть.",
                "Когда просят внести изменение, я проверяю, не создаёт ли оно проблему консистентности с другими экранами.",
            ],
            "data": [
                "Я изучаю карты кликов и записи сессий, чтобы найти части интерфейса, которые пользователи обходят стороной.",
                "После запуска обновления дизайна я проверяю ключевые метрики, чтобы убедиться в ожидаемом эффекте.",
                "Когда есть два варианта макета, я задаю критерий успеха до проведения теста.",
                "Я отслеживаю время выполнения задачи, а не только факт её завершения.",
                "Перед юзабилити-тестом я записываю, что именно будет считаться успехом или неудачей.",
            ],
            "creativity": [
                "Я создаю от трёх до пяти набросков макета, прежде чем выбрать один для детальной проработки.",
                "Когда стандартный UI-паттерн не отвечает нужде пользователя, я предлагаю и тестирую нестандартное решение.",
                "Я использую мудборды для изучения визуальных направлений перед выбором стиля.",
                "На каждом мозговом штурме я включаю хотя бы одну нестандартную идею.",
                "Когда я застреваю на визуальной проблеме, я делаю десять набросков за десять минут.",
            ],
            "people": [
                "Перед началом нового дизайна я провожу хотя бы одно интервью с пользователем.",
                "Когда разработчик говорит, что дизайн сложно реализовать, я прошу показать конкретное ограничение.",
                "Я представляю дизайн с целью пользователя сверху, а не с названием функции.",
                "Я прошу пользователей думать вслух при выполнении задачи, чтобы слышать их рассуждения.",
                "Когда решение основано на пользовательском инсайте, я документирую его для команды.",
            ],
            "technical": [
                "Я могу создать интерактивный прототип в Figma с пятью и более переходами между экранами.",
                "Перед передачей разработчику я проверяю консистентность компонентов и их именование по дизайн-системе.",
                "Я настраиваю auto-layout так, чтобы компоненты корректно масштабировались под разные ширины.",
                "Я знаю разницу между векторными и растровыми форматами и выбираю правильные настройки экспорта.",
                "Когда разработчик спрашивает о реализуемости дизайна, я могу обсудить технические ограничения.",
            ],
        },
        "uz": {
            "logic": [
                "Foydalanuvchi dizaynimdagi vazifani bajara olmasa, vizualni o'zgartirishdan oldin aynan qayerda qotib qolganini topish uchun qadamlarni kuzataman.",
                "Yangi ekran maketi yaratishdan oldin foydalanuvchi maqsadini va uch eng ehtimoliy yo'lini yozib olaman.",
                "Ziddiyatli fikrlar olganda, har birini ustuvorlikni belgilashdan oldin muayyan foydalanuvchi ehtiyojiga bog'layman.",
                "Har bir dizaynda yangi foydalanuvchi ko'rsatmasiz qayerga qarashini biladigan aniq vizual ierarxiya yarataман.",
                "O'zgartirish talab qilinganda, boshqa ekranlar bilan izchillik muammosi yaratmasligini tekshiraman.",
            ],
            "data": [
                "Qayta dizayn qilishdan oldin foydalanuvchilar qaysi interfeйс qismlarini chetlab o'tishini klik xaritalari va seans yozuvlari orqali aniqlayman.",
                "Dizayn yangilanishidan so'ng o'zgarish kutilgan samarani berganini ko'rish uchun asosiy ko'rsatkichlarni tekshiraman.",
                "Ikkita makет variantim bo'lsa, test o'tkazishdan oldin o'lchanadigan muvaffaqiyat mezonini belgilayman.",
                "Vazifani bajarishga ketgan vaqtni ham kuzataman, faqat muvaffaqiyatni emas.",
                "Foydalanish testidan oldin qanday xulq muvaffaqiyat va qanday xulq muvaffaqiyatsizlik bo'lishini yozib qo'yaman.",
            ],
            "creativity": [
                "Bittasini batafsilroq ishlab chiqishni tanlashdan oldin kamida uch-beshta qo'pol makет varianti yarataман.",
                "Standart UI namunasi muayyan foydalanuvchi ehtiyojiga mos kelmasa, maxsus yechim taklif qilib sinab ko'raman.",
                "Uslubga qaror qilishdan oldin vizual yo'nalishlarni o'rganish uchun mood board yoki mos misol to'plamidan foydalanaman.",
                "Har bir miya hujumida kamida bitta noan'anaviy g'oyani kiritishga o'zimni undayman.",
                "Vizual muammoga qotib qolsam, to'siqni engish uchun o'n daqiqada o'nta variant chizaman.",
            ],
            "people": [
                "Yangi dizayn boshlashdan oldin haqiqiy muammolarni aniqlash uchun kamida bitta foydalanuvchi intervyusini o'tkazaman.",
                "Dasturchi dizaynim juda murakkab ekanligini aytsa, birgalikda moslashtirishimiz uchun muayyan cheklovni ko'rsatishini so'rayman.",
                "Dizaynlarni funksiya nomi bilan emas, foydalanuvchi maqsadi bilan boshlab taqdim etaman.",
                "Foydalanuvchilardan vazifani bajarayotganda ovoz chiqarib o'ylashini so'rayman, shunda ularning fikrlarini eshitaman.",
                "Dizayn qarori foydalanuvchi topilmasiga asoslanganda, keyinroq jamoa murojaat qilishi uchun uni hujjatlashtiraman.",
            ],
            "technical": [
                "Figmada kamida beshta turli ekran o'tishini ko'rsatuvchi interaktiv prototip yasay olaman.",
                "Dasturchi topshirishdan oldin barcha komponentlar izchil va dizayn tizimiga ko'ra nomlanganini tekshiraman.",
                "Komponentlar turli ekran kengliklarida to'g'ri o'lchamda ko'rinishi uchun auto-layout sozlayman.",
                "Vektor va rastr formatlar o'rtasidagi farqni tushunam va har bir resurs uchun to'g'ri eksport sozlamasini tanlayman.",
                "Dasturchi dizayn amalga oshirib bo'ladimi deb so'raganda, texnik cheklovlarni muhokama qilib muqobil taklif qila olaman.",
            ],
        },
    },
    "healthcare": {
        "en": {
            "logic": [
                "When a patient presents with multiple symptoms, I list the most likely explanations and rule them out systematically before settling on a conclusion.",
                "Before recommending a treatment, I check whether the evidence behind it applies to this specific patient's age, history, and conditions.",
                "When a clinical situation does not improve as expected, I revisit my initial assessment to find what assumption I may have missed.",
                "I break a complex patient case into smaller clinical questions and address each one before forming an overall care plan.",
                "When two treatment options are both valid, I compare their side-effect profiles and patient preferences before making a recommendation.",
            ],
            "data": [
                "When I receive lab results, I compare them against the reference range and the patient's previous values before drawing conclusions.",
                "I track a patient's vital signs over time rather than reacting to a single abnormal reading.",
                "Before recommending a medication change, I look at the dosing history and check whether adherence was the real issue.",
                "I document clinical findings clearly enough that another clinician could understand the case without asking me.",
                "When reviewing treatment outcomes across a group of patients, I look for patterns that might indicate a systemic issue.",
            ],
            "creativity": [
                "When a patient cannot follow a standard treatment plan, I adapt the approach to fit their daily routine rather than dismissing them as non-compliant.",
                "I look for patient education materials in formats that match how a specific patient actually learns — not just the default handout.",
                "When a clinical workflow is causing delays, I propose a small change to the process and observe whether it helps before scaling it.",
                "I look to other healthcare settings or specialties for ideas when my current approach to a recurring problem is not working.",
                "When a patient is anxious about a procedure, I find a way to reframe it that reduces fear without downplaying risk.",
            ],
            "people": [
                "When explaining a diagnosis to a patient, I use language they can understand and check that they can repeat back the key points.",
                "When a patient disagrees with my recommendation, I ask what concerns are driving their hesitation before repeating my advice.",
                "I brief other team members on a patient handoff with the three most important facts — not every detail — so nothing critical is missed.",
                "When a family member is distressed during a consultation, I acknowledge their concern before continuing with clinical information.",
                "I ask patients what a good outcome looks like to them before assuming I know what they want from treatment.",
            ],
            "technical": [
                "I can accurately perform a patient assessment and document findings in a clinical record without prompting.",
                "Before using a piece of medical equipment, I verify it is calibrated and that I know the correct procedure for this patient's condition.",
                "When writing a clinical note, I include the reasoning behind my decision, not just the decision itself.",
                "I follow infection control protocols consistently, even when the environment is busy and shortcuts are tempting.",
                "I keep my knowledge of clinical guidelines current and can explain when a standard protocol applies and when it does not.",
            ],
        },
        "ru": {
            "logic": [
                "Когда пациент предъявляет несколько симптомов, я составляю список наиболее вероятных причин и последовательно исключаю их до вывода.",
                "Перед назначением лечения я проверяю, применима ли доказательная база к конкретному возрасту, истории и состоянию пациента.",
                "Когда клиническая ситуация не улучшается, я пересматриваю первоначальную оценку в поисках пропущенного допущения.",
                "Сложный клинический случай я разбиваю на небольшие вопросы и отвечаю на каждый до составления общего плана.",
                "Когда два варианта лечения одинаково обоснованы, я сравниваю их побочные эффекты и предпочтения пациента.",
            ],
            "data": [
                "Получая результаты анализов, я сравниваю их с референсными значениями и предыдущими показателями пациента.",
                "Я отслеживаю витальные показатели пациента в динамике, а не реагирую на единичное отклонение.",
                "Перед изменением медикамента я изучаю историю дозировок и проверяю, не связана ли проблема с соблюдением режима.",
                "Я документирую клинические данные так, чтобы другой специалист мог понять случай без вопросов ко мне.",
                "Анализируя результаты лечения группы пациентов, я ищу закономерности, указывающие на системную проблему.",
            ],
            "creativity": [
                "Когда пациент не может следовать стандартному плану, я адаптирую подход под его распорядок дня, а не отношусь к нему как к нарушителю.",
                "Я ищу образовательные материалы в формате, который подходит конкретному пациенту, а не вручаю стандартный листок.",
                "Когда рабочий процесс вызывает задержки, я предлагаю небольшое изменение и наблюдаю, помогает ли оно.",
                "Столкнувшись с повторяющейся проблемой, я ищу идеи в других медицинских учреждениях или специальностях.",
                "Когда пациент тревожится из-за процедуры, я нахожу способ переформулировать её так, чтобы снизить страх, не преуменьшая рисков.",
            ],
            "people": [
                "Объясняя диагноз, я использую понятный язык и проверяю, может ли пациент повторить ключевые моменты.",
                "Когда пациент не соглашается с рекомендацией, я сначала спрашиваю о его опасениях, а не повторяю совет.",
                "При передаче пациента я кратко сообщаю три важнейших факта, чтобы ничего критичного не было упущено.",
                "Когда родственник взволнован на приёме, я сначала признаю его беспокойство, а затем продолжаю с клинической информацией.",
                "Я спрашиваю пациентов, как они видят хороший исход, прежде чем предполагать, чего они хотят от лечения.",
            ],
            "technical": [
                "Я могу провести осмотр пациента и задокументировать данные в медицинской карте без подсказок.",
                "Перед использованием медицинского оборудования я проверяю калибровку и правильную процедуру для данного состояния.",
                "В клинической записи я указываю обоснование решения, а не только само решение.",
                "Я соблюдаю протоколы инфекционного контроля постоянно, даже в напряжённой обстановке.",
                "Я слежу за актуальностью клинических рекомендаций и могу объяснить, когда стандарт применим, а когда нет.",
            ],
        },
        "uz": {
            "logic": [
                "Bemor bir necha simptom ko'rsatganda, xulosaga kelishdan oldin eng ehtimoliy sabablarni ro'yxatga olib, ularni ketma-ket istisno qilaman.",
                "Davolashni tavsiya qilishdan oldin uning dalil bazasi ushbu bemorning yoshi, tarixi va holatiga taalluqli ekanligini tekshiraman.",
                "Klinik holat kutilganidek yaxshilanmasa, qoldirgan farazimni topish uchun dastlabki bahoni qayta ko'rib chiqaman.",
                "Murakkab klinik holatni kichik klinik savollarga bo'lib, umumiy parvarishlash rejasini tuzishdan oldin har birini hal qilaman.",
                "Ikkita teng asosli davolash varianti bo'lsa, tavsiya berishdan oldin ularning yon ta'sirlari va bemorning afzalliklarini solishtiraman.",
            ],
            "data": [
                "Tahlil natijalari kelganda, xulosalar chiqarishdan oldin ularni me'yor ko'rsatkichlari va bemorning avvalgi qiymatlari bilan solishtiraman.",
                "Bemorning hayotiy ko'rsatkichlarini bitta g'ayrioddiy o'qishga emas, vaqt o'tishi bilan kuzataman.",
                "Dorivorni o'zgartirishdan oldin dozalash tarixini ko'rib chiqaman va muammo tartib-qoidaga rioya qilmaslik bilan bog'liqligini tekshiraman.",
                "Klinik xulosalarni boshqa mutaxassis menga savol bermay holatni tushuna oladigan darajada aniq hujjatlashtiraman.",
                "Bemorlar guruhidagi davolash natijalarini ko'rib chiqayotganda, tizimli muammoga ishora qiluvchi naqshlarni qidiraman.",
            ],
            "creativity": [
                "Bemor standart davolash rejasiga amal qila olmasa, uni qoidabuzar deb emas, kundalik tartibiga moslab yondashuvni moslashtiram.",
                "Muayyan bemorga mos o'quv materiallarini standart varaqcha emas, uning o'rganish uslubiga mos formatda qidiraman.",
                "Ish jarayoni kechikishlarga sabab bo'lsa, kichik o'zgarish taklif qilib, kengaytirishdan oldin yordam berishini kuzataman.",
                "Takrorlanuvchi muammo bilan kurashayotganda, boshqa tibbiyot muassasalari yoki mutaxassisliklardan g'oyalar izlayman.",
                "Bemor muolajadan xavotir olsa, xavfni kamaytirmasdan qo'rquvni kamaytiruvchi tarzda qayta ifodalash yo'lini topaman.",
            ],
            "people": [
                "Tashxisni tushuntirayotganda, tushunarli til qo'llamаn va bemor asosiy fikrlarni qaytarib ayta olishini tekshiraman.",
                "Bemor tavsiyamga rozi bo'lmasa, maslahatimni takrorlashdan avval uning ikkilanishini keltirib chiqaruvchi tashvishlar haqida so'rayman.",
                "Bemorni topshirayotganda, boshqa jamoa a'zosiga hech narsa o'tkazib yuborilmasligi uchun uchta eng muhim faktni qisqacha bayon qilaman.",
                "Oila a'zosi muloqot chog'ida g'amgin bo'lsa, klinik ma'lumot bilan davom etishdan avval uning tashvishini tan olaman.",
                "Davolashdan nima kutishlarini taxmin qilishdan oldin bemorlardan yaxshi natija ularga qanday ko'rinishini so'rayman.",
            ],
            "technical": [
                "Bemorni ko'rikdan o'tkazib, klinik yozuvga xulosalarni undamasdan hujjatlashtira olaman.",
                "Tibbiy asbob-uskunadan foydalanishdan oldin uning kalibrlashini va ushbu holat uchun to'g'ri tartibni bilishimni tekshiraman.",
                "Klinik eslatmada faqat qarorni emas, uning asoslanishini ham yozaman.",
                "Muhit band va qisqa yo'l vasvasasi bo'lsa ham, infektsiyani nazorat qilish protokollariga doimiy rioya qilaman.",
                "Klinik ko'rsatmalar bilimlarini dolzarb tutaman va standart protokol qachon qo'llanilishini va qachon qo'llanilmasligini tushuntira olaman.",
            ],
        },
    },
    "marketing": {
        "en": {
            "logic": [
                "Before launching a campaign, I write down the target audience, the one message I want them to remember, and how I will measure success.",
                "When a campaign performs worse than expected, I check which single variable changed most before blaming the creative.",
                "I map out the full customer journey from awareness to purchase before deciding which touchpoint to improve first.",
                "When two campaign strategies seem equally valid, I choose the one that aligns better with the brand's existing perception rather than the one that sounds more exciting.",
                "Before recommending a marketing channel, I check whether the target audience is actually active there rather than assuming it.",
            ],
            "data": [
                "After a campaign ends, I compare performance against the baseline and document what the numbers actually tell me versus what I expected.",
                "When my click-through rate drops, I check whether the audience, creative, or placement changed before making edits.",
                "I set specific KPIs before a campaign launches so the team agrees on what good looks like before results come in.",
                "When interpreting social media metrics, I separate vanity metrics (likes) from business metrics (conversions) in my report.",
                "I run A/B tests on one variable at a time — headline, image, or call to action — rather than changing everything at once.",
            ],
            "creativity": [
                "When a headline is not performing, I rewrite it from the customer's perspective — what they gain — rather than what the product does.",
                "I generate at least five different angles for a campaign concept before choosing one to develop into a brief.",
                "When a competitor campaign gets a strong reaction, I analyse why it worked emotionally before copying the format.",
                "I look outside my industry — at film, art, or unrelated brands — for creative inspiration when I am stuck on a concept.",
                "When a client wants generic content, I propose a specific, unexpected angle with data showing why it will stand out.",
            ],
            "people": [
                "Before writing a single piece of content, I interview or survey real customers to find the exact words they use to describe the problem.",
                "When a client changes the campaign brief midway through, I ask what new information changed their thinking before adjusting the work.",
                "I present campaign results to stakeholders by connecting each metric to a business outcome they care about.",
                "When my creative idea is rejected, I ask what specifically did not fit the brand voice so I can adjust rather than guessing.",
                "I share a draft campaign with someone outside my team and listen to their first reaction before finalising it.",
            ],
            "technical": [
                "I can set up a Google Analytics goal and verify it is tracking conversions correctly before a campaign goes live.",
                "Before scheduling email campaigns, I test them across at least three different email clients and check mobile rendering.",
                "I can build a basic paid ad set with audience targeting, creative, and budget allocation without assistance.",
                "I keep a swipe file of effective ads and analyse what makes each one work before referencing it in my own campaigns.",
                "When a campaign tool or platform changes its interface, I update my workflow before it causes a reporting gap.",
            ],
        },
        "ru": {
            "logic": [
                "Перед запуском кампании я записываю целевую аудиторию, одно ключевое сообщение и способ измерения успеха.",
                "Когда кампания работает хуже ожидаемого, я проверяю, какая переменная изменилась больше всего, прежде чем винить креатив.",
                "Я прописываю весь путь клиента от осведомлённости до покупки перед тем, как выбрать точку для улучшения.",
                "Выбирая между двумя стратегиями, я предпочитаю ту, которая лучше соответствует восприятию бренда, а не ту, что звучит эффектнее.",
                "Рекомендуя канал, я проверяю, активна ли там целевая аудитория, а не исхожу из предположений.",
            ],
            "data": [
                "После завершения кампании я сравниваю результаты с базовыми показателями и документирую, что числа реально говорят.",
                "Когда CTR падает, я проверяю, изменилась ли аудитория, креатив или место размещения, прежде чем вносить правки.",
                "До запуска кампании я устанавливаю конкретные KPI, чтобы команда заранее согласилась с критериями успеха.",
                "Интерпретируя метрики соцсетей, я отделяю тщеславные показатели (лайки) от бизнес-метрик (конверсии).",
                "Я провожу A/B-тесты по одной переменной — заголовку, изображению или CTA — а не меняю всё сразу.",
            ],
            "creativity": [
                "Когда заголовок не работает, я переписываю его с позиции клиента — что он получит, а не что делает продукт.",
                "Перед выбором концепции я генерирую минимум пять разных углов подачи.",
                "Когда кампания конкурента вызывает сильную реакцию, я анализирую её эмоциональный механизм до копирования формата.",
                "Когда я застрял на концепции, я ищу вдохновение за пределами своей отрасли — в кино, искусстве или других брендах.",
                "Когда клиент хочет универсальный контент, я предлагаю конкретный, неожиданный угол с данными, показывающими его эффективность.",
            ],
            "people": [
                "До написания контента я провожу интервью или опросы реальных клиентов, чтобы узнать их язык описания проблемы.",
                "Когда клиент меняет бриф в середине работы, я спрашиваю, какая новая информация изменила его взгляды.",
                "Результаты кампании я представляю стейкхолдерам, связывая каждую метрику с бизнес-целью, которая их волнует.",
                "Когда моя идея отклоняется, я спрашиваю, что именно не соответствует голосу бренда, чтобы скорректировать работу.",
                "Я показываю черновик кампании кому-то за пределами команды и слушаю первую реакцию до финализации.",
            ],
            "technical": [
                "Я могу настроить цель в Google Analytics и убедиться, что конверсии отслеживаются корректно до запуска.",
                "Перед рассылкой email-кампании я тестирую её в трёх разных почтовых клиентах и проверяю мобильный вид.",
                "Я могу самостоятельно настроить базовый рекламный кабинет с аудиторией, креативом и бюджетом.",
                "Я веду свайп-файл эффективных объявлений и анализирую, что делает каждое из них рабочим.",
                "Когда платформа обновляет интерфейс, я обновляю рабочий процесс до появления пробела в отчётности.",
            ],
        },
        "uz": {
            "logic": [
                "Kampaniyani ishga tushirishdan oldin maqsadli auditoriyani, yodda qolishi kerak bo'lgan bitta xabarni va muvaffaqiyatni qanday o'lchashni yozib qo'yaman.",
                "Kampaniya kutilganidan yomon ishlasa, ijodni ayblashdan oldin qaysi bitta o'zgaruvchi eng ko'p o'zgarganini tekshiraman.",
                "Birinchi navbatda qaysi aloqa nuqtasini yaxshilash kerakligini hal qilishdan oldin xaridorgacha bo'lgan to'liq yo'lni xaritalashtiram.",
                "Ikkita teng asosli strategiya bo'lsa, qiziqroq eshitilganini emas, brend mavjud idrokiga yaxshiroq mos keladiganini tanlayman.",
                "Marketing kanalini tavsiya qilishdan oldin maqsadli auditoriya u yerda faol ekanligini taxmin qilmasdan tekshiraman.",
            ],
            "data": [
                "Kampaniya tugagach, natijalarni bazaviy ko'rsatkichlar bilan solishtirib, raqamlar menga aslida nima aytayotganini hujjatlashtiraman.",
                "Bosish darajam pasayganda, tahrirlashdan oldin auditoriya, ijod yoki joylashtirish o'zgarganini tekshiraman.",
                "Natijalar kelishidan oldin jamoa yaxshilik nima ekanligiga rozi bo'lishi uchun kampaniya ishga tushishidan oldin aniq KPI'lar belgilayman.",
                "Ijtimoiy media ko'rsatkichlarini tahlil qilganda, hisobotimda tasviriy ko'rsatkichlarni (layklar) biznes ko'rsatkichlaridan (konversiyalar) ajrataman.",
                "Sarlavha, rasm yoki harakat chaqiruvi — bir vaqtda hamma narsani emas, bittadan o'zgaruvchini A/B test qilaman.",
            ],
            "creativity": [
                "Sarlavha ishlamayotganda, mahsulot nima qilishidan emas, mijoz nima olishidan — mijoz nuqtai nazaridan qayta yozaman.",
                "Bitta ishlab chiqishdan oldin kampaniya konsepsiyasi uchun kamida beshta turli burchak yarataман.",
                "Raqib kampaniyasi kuchli reaksiya olganda, formatni nusxa ko'chirishdan oldin u emotsional jihatdan nima uchun ishlashini tahlil qilaman.",
                "Konsepsiyaga qotib qolsam, sanoatimdan tashqarida — kino, san'at yoki bog'liq bo'lmagan brendlarda ilhom izlayman.",
                "Mijoz umumiy kontent istasa, ajralib turishi sabablarini ko'rsatadigan ma'lumotlar bilan aniq, kutilmagan burchak taklif qilaman.",
            ],
            "people": [
                "Bitta kontent yozishdan oldin muammoni ta'riflashda ishlatiladigan aniq so'zlarni topish uchun haqiqiy mijozlarni intervyuga olaman yoki so'rovnoma o'tkazaman.",
                "Mijoz kampaniya tz'mini o'rtada o'zgartirsa, ishni moslashtirish oldidan fikrlarini o'zgartirgan yangi ma'lumot haqida so'rayman.",
                "Kampaniya natijalarini manfaatdor tomonlarga ularni qiziqtiradigan biznes natijasiga har bir ko'rsatkichni bog'lab taqdim etaman.",
                "Ijodiy g'oyam rad etilganda, ishni moslashtirishim uchun brend ovoziga aniq nima mos kelmaganini so'rayman.",
                "Uni yakunlashdan oldin kampaniya qoralamасini jamoadagi bo'lmagan kimgadir ko'rsatib, birinchi reaksiyani tinglayman.",
            ],
            "technical": [
                "Google Analytics maqsadini sozlab, kampaniya ishga tushishidan oldin konversiyalar to'g'ri kuzatilayotganini tekshira olaman.",
                "Email kampaniyalarini rejalashtirish oldidan kamida uchta turli email mijozida sinab ko'raman va mobil ko'rinishini tekshiraman.",
                "Yordamsiz auditoriya maqsadlash, ijod va byudjet taqsimoti bilan asosiy pulli reklama to'plamini yarataолаman.",
                "Samarali reklamalarning swipe faylini saqlayman va o'z kampaniyalarimda murojaat qilishdan oldin har birini nima samarali qilishini tahlil qilaman.",
                "Kampaniya vositasi yoki platformasi interfeysini o'zgartirsa, hisobotda bo'shliq paydo bo'lishidan oldin ish jarayonimni yangilayman.",
            ],
        },
    },
    "finance": {
        "en": {
            "logic": [
                "Before building a financial model, I write down the key assumptions I am making and what evidence supports each one.",
                "When two investment options have similar returns, I compare their risk profiles and liquidity before making a recommendation.",
                "When a financial projection does not match actual results, I trace back through each assumption to find where the model diverged from reality.",
                "I break a complex valuation into its component parts — revenue, costs, discount rate — and validate each before combining them.",
                "When a client asks whether a business is profitable, I distinguish between accounting profit and cash flow before answering.",
            ],
            "data": [
                "Before presenting a financial recommendation, I verify the source data for errors, inconsistencies, and outdated entries.",
                "When analysing a company's financial health, I compare its ratios against industry benchmarks rather than absolute numbers alone.",
                "I build a sensitivity table to show how the conclusion changes when one key assumption is wrong by 10 or 20 percent.",
                "When a number in a report looks unusual, I trace it back to the original source before accepting it.",
                "I track my financial forecasts against actual results each month and document why they diverged.",
            ],
            "creativity": [
                "When a standard valuation method does not apply to a new type of business, I research alternative approaches and document my reasoning.",
                "When a client's budget is too tight for their goals, I find a restructuring option they had not considered.",
                "I look at how analogous companies in different industries were valued to find a comparison point when no direct peer exists.",
                "When a regulatory change affects a financial model, I build a scenario that shows the range of outcomes rather than a single point estimate.",
                "I design financial reports as decision-making tools — not just number summaries — by structuring them around the key question.",
            ],
            "people": [
                "When presenting financial data to a non-finance audience, I translate key numbers into business language they already understand.",
                "When a client resists a financially sound recommendation, I ask what outcome they are most afraid of before re-explaining the numbers.",
                "I write financial reports so that the executive summary answers the decision-maker's question without requiring them to read the full document.",
                "When a colleague's financial analysis contains an error, I raise it privately with a specific example rather than correcting it publicly.",
                "I check that every stakeholder who will be affected by a financial decision has been consulted before it is finalised.",
            ],
            "technical": [
                "I can build a three-statement financial model in Excel — income statement, balance sheet, and cash flow — and verify that they reconcile.",
                "Before sharing a spreadsheet, I check for broken formula links, hardcoded numbers in formula cells, and circular references.",
                "I can use VLOOKUP, INDEX-MATCH, and pivot tables to extract and summarise data without manual copy-paste.",
                "I organise financial models with a clear input section, calculation section, and output section so anyone can audit them.",
                "When I inherit a financial model from someone else, I trace the key formulas before relying on its outputs.",
            ],
        },
        "ru": {
            "logic": [
                "Перед построением финансовой модели я записываю ключевые допущения и доказательства, их подтверждающие.",
                "Когда два варианта инвестиций имеют схожую доходность, я сравниваю их риск и ликвидность до рекомендации.",
                "Когда прогноз расходится с фактом, я прослеживаю каждое допущение, чтобы найти точку расхождения.",
                "Сложную оценку я разбиваю на компоненты — выручку, затраты, ставку дисконта — и проверяю каждый до объединения.",
                "Когда клиент спрашивает, прибыльна ли компания, я разграничиваю бухгалтерскую прибыль и денежный поток до ответа.",
            ],
            "data": [
                "Перед представлением финансовой рекомендации я проверяю исходные данные на ошибки и устаревшие записи.",
                "Анализируя финансовое состояние компании, я сравниваю коэффициенты с отраслевыми ориентирами.",
                "Я строю таблицу чувствительности, показывающую, как вывод меняется при ошибке в 10-20% по ключевому допущению.",
                "Когда число в отчёте выглядит необычно, я прослеживаю его до первоисточника до принятия.",
                "Я ежемесячно сравниваю финансовые прогнозы с фактом и документирую причины расхождения.",
            ],
            "creativity": [
                "Когда стандартный метод оценки не подходит для нового типа бизнеса, я ищу альтернативы и документирую логику.",
                "Когда бюджет клиента слишком мал для его целей, я нахожу вариант реструктуризации, о котором он не думал.",
                "При отсутствии прямых аналогов я ищу компании из других отраслей для точки сравнения.",
                "Когда регуляторное изменение влияет на модель, я строю сценарий с диапазоном исходов, а не точечную оценку.",
                "Я проектирую финансовые отчёты как инструменты принятия решений, структурируя их вокруг ключевого вопроса.",
            ],
            "people": [
                "Представляя финансовые данные нефинансовой аудитории, я перевожу ключевые цифры на понятный деловой язык.",
                "Когда клиент сопротивляется обоснованной рекомендации, я спрашиваю, какого исхода он больше всего боится.",
                "Финансовые отчёты я пишу так, чтобы резюме отвечало на вопрос руководителя без чтения всего документа.",
                "Когда анализ коллеги содержит ошибку, я указываю на неё приватно с конкретным примером.",
                "Я убеждаюсь, что все, кого затронет финансовое решение, были проконсультированы до его финализации.",
            ],
            "technical": [
                "Я могу построить трёхзвенную финансовую модель в Excel и проверить, что все части согласуются.",
                "Перед отправкой таблицы я проверяю битые ссылки, захардкоженные числа в ячейках формул и циклические ссылки.",
                "Я умею использовать ВПР, INDEX-MATCH и сводные таблицы для извлечения и обобщения данных без ручного копирования.",
                "Финансовые модели я организую с чёткими секциями ввода, расчёта и вывода, чтобы их мог проверить любой.",
                "Получив чужую модель, я прослеживаю ключевые формулы до того, как полагаться на её результаты.",
            ],
        },
        "uz": {
            "logic": [
                "Moliyaviy model qurish oldidan asosiy farazlarimni va ularni qo'llab-quvvatlovchi dalillarni yozib qo'yaman.",
                "Ikkita investitsiya varianti o'xshash daromad ko'rsatsa, tavsiya berishdan oldin ularning risk profili va likvidliligini solishtiraman.",
                "Moliyaviy bashorat haqiqiy natijaga mos kelmasa, model qayerda haqiqatdan uzoqlashganini topish uchun har bir farazni kuzataman.",
                "Murakkab baholashni komponentlariga — daromad, xarajatlar, diskont stavkasi — bo'lib, birlashtirish oldidan har birini tekshiraman.",
                "Mijoz biznes daromadli ekanligini so'raganda, javob berishdan oldin buxgalteriya foydasini pul oqimidan ajrataman.",
            ],
            "data": [
                "Moliyaviy tavsiya taqdim etishdan oldin manba ma'lumotlarini xatolar, nomuvofiqliklar va eskirgan yozuvlar uchun tekshiraman.",
                "Kompaniyaning moliyaviy salomatligini tahlil qilganda, uning koeffitsientlarini mutlaq raqamlar bilan emas, sanoat me'yorlari bilan solishtiraman.",
                "Asosiy faraz 10 yoki 20 foizga noto'g'ri bo'lganda xulosaning qanday o'zgarishini ko'rsatuvchi sezuvchanlik jadvalini yarataман.",
                "Hisobotdagi raqam g'ayrioddiy ko'rinsa, uni qabul qilishdan oldin asl manbaiga qaytib kuzataman.",
                "Moliyaviy bashoratlarimni har oyda haqiqiy natijalar bilan solishtirib, nima uchun farq qilganini hujjatlashtiraman.",
            ],
            "creativity": [
                "Standart baholash usuli yangi turdagi biznesga mos kelmasa, muqobil yondashuvlarni tadqiq etib, mantiqimni hujjatlashtiraman.",
                "Mijoz byudjeti maqsadlari uchun etarli bo'lmasa, u o'ylamagan qayta tuzish variantini topaman.",
                "To'g'ridan-to'g'ri tengdosh bo'lmagan hollarda taqqoslash nuqtasini topish uchun boshqa sohalardagi o'xshash kompaniyalar qanday baholanganligi kuzataman.",
                "Tartibga solish o'zgarishi moliyaviy modelga ta'sir qilganda, bitta nuqtali baholash o'rniga natijalar diapazonini ko'rsatuvchi senariy quraman.",
                "Moliyaviy hisobotlarni faqat raqamlar xulosasi emas, balki qaror qabul qilish vositasi sifatida — asosiy savolga qaratib tuzaman.",
            ],
            "people": [
                "Moliyaviy ma'lumotlarni moliya bo'lmagan auditoriyaga taqdim etganda, asosiy raqamlarni ular allaqachon tushunadigan biznes tiliga tarjima qilaman.",
                "Mijoz moliyaviy jihatdan asosli tavsiyaga qarshilik qilsa, raqamlarni qayta tushuntirishdan oldin u qanday natijadan ko'proq qo'rqishini so'rayman.",
                "Moliyaviy hisobotlarni shunday yozamanki, ijroiya xulosasi qaror qabul qiluvchining savolini to'liq hujjatni o'qishni talab qilmasdan javoblaydi.",
                "Hamkasb tahlilida xato bo'lsa, uni ommaviy ravishda emas, muayyan misol bilan shaxsan bildiraman.",
                "Moliyaviy qaror yakunlashtirilishidan oldin u ta'sir qiladigan barcha manfaatdor tomonlar maslahat olganini tekshiraman.",
            ],
            "technical": [
                "Excelda uch qismli moliyaviy model — daromadlar va xarajatlar, balans, pul oqimi — qurib, ularning kelishuvchanligini tekshira olaman.",
                "Jadvalvalaqni ulashishdan oldin buzilgan formula havollari, formula katakchalardagi qo'lda kiritilgan raqamlar va doiraviy havolalarni tekshiraman.",
                "Qo'lda nusxa ko'chirmasdan ma'lumotlarni ajratib olish va umumlashtirish uchun VLOOKUP, INDEX-MATCH va pivot jadvalaridan foydalana olaman.",
                "Moliyaviy modellarni aniq kirish, hisoblash va chiqish bo'limlari bilan tartiblamanki, har kim ularni tekshira olsin.",
                "Birovning modelini olganimda, uning natijalariga tayalishdan oldin asosiy formulalarni kuzataman.",
            ],
        },
    },
    "engineering": {
        "en": {
            "logic": [
                "Before selecting a material or component, I calculate whether it meets the load and safety requirements rather than estimating by feel.",
                "When a design fails during testing, I identify the root cause rather than modifying the symptom and moving on.",
                "I break a large engineering problem into sub-systems, verify each independently, and then check how they interact.",
                "When two design solutions meet the requirement, I compare cost, weight, manufacturability, and maintenance before recommending one.",
                "Before finalising a design, I check it against the original specification to confirm every requirement is addressed.",
            ],
            "data": [
                "I document all test results — including failed runs — so the team can learn from experiments that did not work.",
                "Before trusting a simulation result, I check the boundary conditions and mesh quality against known validation cases.",
                "When a measurement seems off, I check the sensor calibration and repeat the measurement before concluding there is a fault.",
                "I use tolerancing and statistical analysis to understand the range of acceptable variation in a manufactured part.",
                "When reviewing engineering drawings, I check dimensions and tolerances for internal consistency before approving them.",
            ],
            "creativity": [
                "When a design constraint seems impossible to meet, I explore whether relaxing a different constraint opens up new options.",
                "I sketch at least three alternative concepts before committing to a detailed design, even when the first idea seems obvious.",
                "When an existing component does not meet requirements, I investigate whether a modified standard part would work before designing custom.",
                "I look at solutions from adjacent industries — aerospace, automotive, medical — for ideas when I am stuck on a mechanical problem.",
                "When a product must be lighter or cheaper, I challenge every component's purpose before removing or simplifying any single one.",
            ],
            "people": [
                "When a non-engineer asks about a design decision, I explain the trade-offs in terms of outcomes they care about — cost, safety, delivery — not formulas.",
                "Before handing a design to manufacturing, I discuss the drawing with a machinist or fabricator to catch producibility issues early.",
                "When a project deadline is at risk, I communicate the specific bottleneck and a proposed solution rather than just reporting a delay.",
                "I document design decisions in a way that someone joining the project six months later can understand the reasoning without asking.",
                "When a client requests a change that would weaken safety margins, I explain the risk clearly in writing before proceeding.",
            ],
            "technical": [
                "I can create a dimensioned drawing or CAD model that another engineer could manufacture without needing to ask me for clarification.",
                "Before running a physical test, I predict the expected outcome so I can immediately identify whether the result is anomalous.",
                "I follow engineering standards and codes relevant to my domain and know where to look when a standard does not cover my case.",
                "I verify units and unit conversions in every calculation before using the result in a design decision.",
                "When a tool or software gives an unexpected output, I validate it with a hand calculation or known reference case before relying on it.",
            ],
        },
        "ru": {
            "logic": [
                "Перед выбором материала или компонента я рассчитываю, соответствует ли он требованиям нагрузки и безопасности.",
                "Когда конструкция не проходит испытание, я нахожу коренную причину, а не исправляю симптом.",
                "Большую инженерную задачу я разбиваю на подсистемы, проверяю каждую независимо, затем проверяю взаимодействие.",
                "Когда два решения соответствуют требованиям, я сравниваю стоимость, вес, производимость и обслуживание.",
                "Перед финализацией конструкции я сверяю её с исходным техзаданием, чтобы убедиться, что все требования учтены.",
            ],
            "data": [
                "Я документирую все результаты испытаний, включая неудачные, чтобы команда могла учиться на них.",
                "Прежде чем доверять результату симуляции, я проверяю граничные условия и качество сетки.",
                "Когда измерение кажется неточным, я проверяю калибровку датчика и повторяю измерение.",
                "Я применяю допуски и статистический анализ для понимания допустимого разброса в производстве.",
                "Проверяя чертежи, я контролирую внутреннюю согласованность размеров и допусков до утверждения.",
            ],
            "creativity": [
                "Когда ограничение кажется невозможным, я проверяю, открывает ли ослабление другого ограничения новые возможности.",
                "Я делаю минимум три альтернативных концепта до перехода к детальному проектированию, даже если первая идея очевидна.",
                "Когда стандартный компонент не отвечает требованиям, я изучаю, можно ли модифицировать стандартную деталь вместо разработки заказной.",
                "Застряв на механической проблеме, я ищу решения в смежных отраслях — авиации, автомобилестроении, медтехнике.",
                "Когда изделие должно быть легче или дешевле, я оспариваю назначение каждого компонента перед упрощением любого из них.",
            ],
            "people": [
                "Объясняя конструктивное решение неинженеру, я говорю о результатах — стоимости, безопасности, сроках, а не формулах.",
                "До передачи чертежей в производство я обсуждаю их с механиком или производственником для раннего выявления проблем.",
                "Когда срок проекта под угрозой, я сообщаю о конкретном узком месте и предлагаемом решении, а не просто о задержке.",
                "Конструктивные решения я документирую так, чтобы инженер, пришедший через полгода, понял логику без вопросов.",
                "Когда клиент запрашивает изменение, снижающее запас прочности, я письменно объясняю риск до выполнения.",
            ],
            "technical": [
                "Я могу создать размерный чертёж или CAD-модель, по которым другой инженер может изготовить деталь без уточнений.",
                "Перед физическим испытанием я предсказываю ожидаемый результат, чтобы сразу заметить аномальный итог.",
                "Я следую инженерным стандартам своей области и знаю, куда обратиться, когда стандарт не покрывает мой случай.",
                "В каждом расчёте я проверяю единицы измерения и конверсии до использования в конструктивном решении.",
                "Когда инструмент или программа выдают неожиданный результат, я проверяю его ручным расчётом до применения.",
            ],
        },
        "uz": {
            "logic": [
                "Material yoki komponent tanlashdan oldin uning yuk va xavfsizlik talablariga javob berishini his bilan emas, hisoblash bilan tekshiraman.",
                "Dizayn test paytida muvaffaqiyatsiz bo'lsa, alomata ta'sir qilish va davom etish o'rniga asosiy sababni aniqlayman.",
                "Katta muhandislik muammosini kichik tizimchalarga bo'lib, har birini mustaqil tekshiraman, keyin o'zaro ta'sirini tekshiraman.",
                "Ikkita dizayn yechimi talabga javob bersa, birini tavsiya qilishdan oldin narx, og'irlik, ishlab chiqarish qulayligi va texnik xizmatni solishtiraman.",
                "Dizaynni yakunlashdan oldin har bir talab ko'rib chiqilganligini tasdiqlash uchun uni asl texnik vazifaga nisbatan tekshiraman.",
            ],
            "data": [
                "Jamoa muvaffaqiyatsiz tajribalardan ham o'rgana olishi uchun barcha sinov natijalarini, jumladan muvaffaqiyatsizlarini hujjatlashtiraman.",
                "Simulyatsiya natijasiga ishonishdan oldin cheklov shartlari va to'r sifatini ma'lum tekshirish holatlari bilan solishtirib tekshiraman.",
                "O'lchov noto'g'ri ko'rinsa, nosozlik borligini tasdiqlashdan oldin sensor kalibrovkasini tekshirib, o'lchovni takrorlayman.",
                "Ishlab chiqarilgan qismda qabul qilinadigan o'zgarish diapazonini tushunish uchun toleranslashtirish va statistik tahlildan foydalanaman.",
                "Muhandislik chizmalarini ko'rib chiqayotganda, ularni tasdiqlashdan oldin o'lchamlar va toleranslarning ichki kelishuvini tekshiraman.",
            ],
            "creativity": [
                "Dizayn cheklovi bajarib bo'lmaydigan ko'rinsa, boshqa cheklovni yumshatish yangi imkoniyatlar ochishini tekshiraman.",
                "Birinchi g'oya aniq bo'lsa ham, batafsil dizaynga o'tishdan oldin kamida uchta muqobil konsepsiya chizaman.",
                "Mavjud komponent talablarga javob bermasa, maxsus loyihalashtirish oldidan modifikatsiya qilingan standart qism mos bo'lmasligini o'rganaman.",
                "Mexanik muammoda qotib qolsam, aviatsiya, avtomobilsozlik, tibbiy texnikadan g'oyalar qidiraman.",
                "Mahsulot engil yoki arzon bo'lishi kerak bo'lsa, har birini soddalashtirish oldidan har bir komponentning maqsadini so'roq ostiga olaman.",
            ],
            "people": [
                "Muhandis bo'lmagan kishi dizayn qarorini so'raganda, formulalar emas, ularga muhim natijalar — narx, xavfsizlik, yetkazib berish — bo'yicha tushuntiraman.",
                "Dizaynni ishlab chiqarishga topshirishdan oldin ishlab chiqarish muammolarini erta aniqlash uchun chizmani usta yoki toychiq bilan muhokama qilaman.",
                "Loyiha muddati xavf ostida bo'lganda, faqat kechikishni emas, muayyan to'siqni va taklif etilgan yechimni bildiraman.",
                "Dizayn qarorlarini olti oy keyin loyihaga qo'shilgan kishi mendan so'ramasdan mantiqni tushuna oladigan tarzda hujjatlashtiraman.",
                "Mijoz xavfsizlik zaxiralarini kamaytiruvchi o'zgartirish so'raganda, davom etishdan oldin xatarni yozma ravishda aniq tushuntiraman.",
            ],
            "technical": [
                "Boshqa muhandis mening ko'rsatmalarimni aniqlashtirmasdan ishlab chiqarishi mumkin bo'lgan o'lchamli chizma yoki CAD modeli yarata olaman.",
                "Jismoniy sinovdan oldin kutilgan natijani bashorat qilaman, shu tarzda natija g'ayritabiiy ekanligini darhol aniqlay olaman.",
                "Sohama tegishli muhandislik standartlari va me'yorlariga rioya qilaman hamda standart mening holatimni qamrab olmaganda qayerga murojaat qilishni bilaman.",
                "Har bir hisobda dizayn qarorida foydalanishdan oldin o'lchov birliklarini va birlikni konvertatsiya qilishni tekshiraman.",
                "Asbob yoki dastur kutilmagan natija berganda, unga tayanishdan oldin qo'lda hisoblash yoki ma'lum ma'lumotnoma holati bilan tekshiraman.",
            ],
        },
    },
    "education": {
        "en": {
            "logic": [
                "Before designing a lesson, I write down the specific skill or knowledge the learner should be able to demonstrate by the end.",
                "When a teaching method is not working for a student, I try to identify whether the issue is motivation, prior knowledge, or the instruction method itself.",
                "I sequence learning objectives so that each lesson builds on the previous one before introducing new complexity.",
                "When two approaches to teaching the same concept are both valid, I choose the one that requires the learner to actively apply the idea rather than passively receive it.",
                "Before creating an assessment, I map each question back to a specific learning objective to verify the test actually measures what I taught.",
            ],
            "data": [
                "I track individual student progress over time rather than relying on a single test score to judge their understanding.",
                "When a whole class struggles with the same concept, I look at my instructional data to see whether the issue started in a prior lesson.",
                "I use formative checks — exit tickets, quick polls, short tasks — to find out what students understand before the end of a unit.",
                "When I design an assessment, I analyse the results to identify whether low scores reflect learning gaps or poorly worded questions.",
                "I keep notes on which teaching strategies produced observable improvements so I can repeat what works.",
            ],
            "creativity": [
                "When a standard lesson format is not engaging a particular group, I redesign the activity so students produce something rather than just receive information.",
                "I find an analogy or real-world example that connects a difficult concept to something students already understand.",
                "When students lose interest midway through a topic, I introduce a problem or challenge that gives the material immediate relevance.",
                "I design projects that allow students to demonstrate learning in more than one format — writing, building, presenting — so different strengths can show.",
                "When I inherit a curriculum I did not design, I find one place where I can add something genuinely engaging rather than delivering it as-is.",
            ],
            "people": [
                "When a student is disengaged, I have a private conversation to understand what is getting in the way before adjusting my approach.",
                "I give feedback on student work that names a specific strength and one specific next step, rather than general praise or criticism.",
                "When a parent is concerned about their child's progress, I share specific evidence of what the student can and cannot do yet.",
                "I adapt the way I explain a concept when I notice a student's face showing confusion, rather than repeating the same explanation louder.",
                "I build time into my planning for students to ask questions and discuss, rather than talking for the full session.",
            ],
            "technical": [
                "I can design an assessment rubric that two different evaluators would score consistently without needing to consult each other.",
                "I use the available technology — LMS, interactive tools, video — in a way that genuinely improves learning rather than just adding novelty.",
                "When I create instructional materials, I check that the reading level and vocabulary match the audience before distributing them.",
                "I organise lesson resources so a substitute teacher could deliver the session effectively using only what I have prepared.",
                "I test any technology I plan to use in a lesson before the session starts to avoid losing teaching time to technical problems.",
            ],
        },
        "ru": {
            "logic": [
                "Перед разработкой урока я записываю конкретный навык или знание, которое ученик должен уметь продемонстрировать по итогу.",
                "Когда метод обучения не работает для ученика, я стараюсь понять, проблема в мотивации, базовых знаниях или самом методе.",
                "Я выстраиваю последовательность целей обучения так, чтобы каждый урок опирался на предыдущий до введения нового.",
                "Выбирая между двумя подходами к одному понятию, я предпочитаю тот, что требует активного применения, а не пассивного восприятия.",
                "Перед созданием оценки я соотношу каждый вопрос с конкретной учебной целью, чтобы тест измерял то, чему я учил.",
            ],
            "data": [
                "Я отслеживаю прогресс каждого ученика во времени, а не полагаюсь на один тест для оценки понимания.",
                "Когда весь класс испытывает трудности с одним понятием, я анализирую данные, чтобы найти, где проблема началась.",
                "Я использую формативные проверки — карточки выхода, быстрые опросы — чтобы до конца темы понять, что усвоено.",
                "Разрабатывая оценку, я анализирую результаты, чтобы понять, отражают ли низкие баллы пробелы или плохие вопросы.",
                "Я записываю, какие стратегии дали заметные улучшения, чтобы повторять то, что работает.",
            ],
            "creativity": [
                "Когда стандартный формат не вовлекает группу, я переделываю задание так, чтобы ученики что-то создавали, а не только получали информацию.",
                "Я нахожу аналогию или реальный пример, связывающий трудное понятие с тем, что ученики уже знают.",
                "Когда интерес к теме угасает, я ввожу задачу или вызов, дающий материалу немедленную актуальность.",
                "Я проектирую проекты, позволяющие ученикам демонстрировать знания в разных форматах — письменно, практически, устно.",
                "Получив чужую программу, я нахожу одно место, куда могу добавить что-то действительно вовлекающее.",
            ],
            "people": [
                "Когда ученик теряет вовлечённость, я веду приватную беседу для понимания причин до изменения подхода.",
                "Обратную связь по работе ученика я формулирую с конкретной сильной стороной и одним конкретным следующим шагом.",
                "Когда родитель беспокоится об успеваемости, я показываю конкретные факты о том, что ученик умеет и что ещё нет.",
                "Замечая растерянность на лице ученика, я адаптирую объяснение, а не повторяю то же самое громче.",
                "В планировании я выделяю время для вопросов и обсуждения, а не говорю сам всё занятие.",
            ],
            "technical": [
                "Я могу разработать рубрику оценивания, по которой два разных проверяющих выставят оценки согласованно.",
                "Я использую доступные технологии — LMS, интерактивные инструменты, видео — так, чтобы они реально улучшали обучение.",
                "Создавая учебные материалы, я проверяю уровень чтения и словарный запас на соответствие аудитории.",
                "Я организую ресурсы урока так, чтобы замещающий учитель мог провести занятие только по моим материалам.",
                "Технологии, которые я планирую использовать, я тестирую до занятия, чтобы не терять учебное время на технические проблемы.",
            ],
        },
        "uz": {
            "logic": [
                "Darsni loyihalashtirish oldidan o'quvchi oxirida ko'rsata olishi kerak bo'lgan muayyan ko'nikma yoki bilimni yozib qo'yaman.",
                "O'qitish usuli o'quvchi uchun ishlamayotganda, muammoning sababi motivatsiya, avvalgi bilim yoki o'qitish usulining o'zi ekanligini aniqlayman.",
                "Yangi murakkablikni kiritishdan oldin har bir dars avvalgisiga asoslanishi uchun o'quv maqsadlarini ketma-ket joylashtiraman.",
                "Bir tushunchani o'rgatishning ikkita yondashuvi ham to'g'ri bo'lsa, passiv qabul qilish emas, faol qo'llashni talab qiladiganini tanlayman.",
                "Baholash yaratishdan oldin test aslida o'rgatganimni o'lchashini tekshirish uchun har bir savolni muayyan o'quv maqsadiga bog'layman.",
            ],
            "data": [
                "O'quvchilarning tushunishini baholash uchun bitta test ballidan emas, vaqt o'tishi bilan individual progressni kuzataman.",
                "Butun sinf bir tushunchaga qiynalsa, muammo avvalgi darsda qachon boshlanganini ko'rish uchun o'qitish ma'lumotlarimga qarayman.",
                "Bo'lim oxirigacha o'quvchilar nima tushunganini bilish uchun chiqish kartochkalari, tezkor so'rovnomalar kabi formativ tekshiruvlardan foydalanaman.",
                "Baholash yaratganimda, past ballar o'quv bo'shliqlarini yoki noto'g'ri ifodalangan savollarni aks ettirishini aniqlayman.",
                "Kuzatilishi mumkin bo'lgan yaxshilanishlarni ta'minlagan o'qitish strategiyalarini yozib qo'yamanki, nima ishlayotganini takrorlashim mumkin bo'lsin.",
            ],
            "creativity": [
                "Standart dars formati muayyan guruhni jalb etmayotganda, o'quvchilar faqat ma'lumot emas, biror narsa yaratadigan tarzda faoliyatni qayta loyihalashtiram.",
                "Qiyin tushunchani o'quvchilar allaqachon tushunadigan narsa bilan bog'laydigan o'xshashlik yoki real misol topaman.",
                "O'quvchilar mavzu o'rtasida qiziqishini yo'qotsa, materialni darhol dolzarb qiladigan muammo yoki musobaqa kiritaman.",
                "Turli kuchlar ko'rinishi uchun o'quvchilar o'qishni bir nechta formatda — yozish, qurish, taqdim etish — ko'rsata oladigan loyihalar loyihalashtiraman.",
                "O'zim loyihalashtirmagan dastur olganda, uni aynan shu holda yetkazish o'rniga haqiqatan jalb qiluvchi biror narsa qo'sha oladigan joy topaman.",
            ],
            "people": [
                "O'quvchi jalb etilmayotganda, yondashuvimni o'zgartirishdan oldin yo'lni to'suvchi narsani tushunish uchun maxfiy suhbat o'tkazaman.",
                "O'quvchi ishiga umumiy maqtov yoki tanqid emas, muayyan kuchli tomon va bitta muayyan keyingi qadamni nomlagan fikr-mulohaza beraman.",
                "Ota-ona farzandining progressidan xavotir olsa, o'quvchi nima qila olishi va hali nima qila olmasligining muayyan dalillarini ulashaman.",
                "O'quvchi yuzida chalg'ishni sezganimda, bir xil tushuntirishni balandroq takrorlash o'rniga tushuntirishni moslashtiraman.",
                "Rejalashtirmamda butun sessiyani o'zim gapirish o'rniga o'quvchilar savol berib muhokama qilishi uchun vaqt ajrataman.",
            ],
            "technical": [
                "Ikkita turli baholovchi bir-biriga murojaat qilmasdan bir xil ball qo'ya oladigan baholash rubriki loyihalashtira olaman.",
                "Mavjud texnologiyalardan — LMS, interaktiv vositalar, video — faqat yangilik qo'shish emas, o'qishni haqiqatan yaxshilaydigan tarzda foydalanaman.",
                "O'quv materiallari yaratganimda, ularni tarqatishdan oldin o'qish darajasi va lug'at auditoriyaga mos ekanligini tekshiraman.",
                "Dars resurslarini shunday tartiblamanki, almashtiradigan o'qituvchi faqat men tayyorlagan narsalar bilan samarali dars o'tkaza olsin.",
                "Darsda ishlatmoqchi bo'lgan texnologiyalarni sessiya boshlanishidan oldin texnik muammolar tufayli o'qitish vaqtini yo'qotmaslik uchun sinayman.",
            ],
        },
    },
    "business": {
        "en": {
            "logic": [
                "Before recommending a business strategy, I identify the key assumption it depends on and what would have to be true for it to fail.",
                "When a business metric declines, I separate the external factors I cannot control from the internal factors I can before deciding what to change.",
                "I build decision trees for high-stakes choices, mapping the likely outcomes of each option before committing resources.",
                "When a project scope is too large for the available resources, I identify the minimum version that still delivers the core value.",
                "Before proposing a new initiative, I check whether an existing process, team, or tool could do the job with a small change rather than building from scratch.",
            ],
            "data": [
                "Before presenting a business recommendation, I verify that my data is recent, relevant, and sourced from a credible place.",
                "When I see a business trend, I check whether it is statistically significant or a short-term fluctuation before drawing conclusions.",
                "I define the two or three metrics that matter most for a goal before tracking twenty and losing focus.",
                "When a business case relies on a key number, I build a range — optimistic, realistic, pessimistic — rather than presenting one figure.",
                "I check competitor data and market benchmarks before claiming that our performance is strong or weak.",
            ],
            "creativity": [
                "When a standard business model does not fit a new market, I combine elements from two different industries to propose something new.",
                "I generate three to five distinct strategic options for a client before presenting the one I recommend.",
                "When a product is losing market share, I look for the job customers are actually hiring it to do before redesigning it.",
                "I look for business problems that others have dismissed as unsolvable, because they often hide opportunities with limited competition.",
                "When resources are constrained, I find a way to test the core assumption of a strategy cheaply before committing full budget.",
            ],
            "people": [
                "When I need stakeholder buy-in for a decision, I identify each person's main concern and address it before presenting the full proposal.",
                "When a team disagrees on priorities, I facilitate a structured conversation that surfaces the trade-offs rather than imposing a decision.",
                "I present business proposals with the recommendation first, then the supporting evidence, so the decision-maker can engage immediately.",
                "When a project is delayed, I proactively communicate the updated timeline and revised plan rather than waiting to be asked.",
                "I adapt my communication style for the audience — executive summary for leaders, detailed breakdown for analysts — without losing accuracy.",
            ],
            "technical": [
                "I can build a business case document — problem, options, recommendation, financials, risks — that a senior leader could review in ten minutes.",
                "I use a project management tool to track tasks, owners, and deadlines so that nothing falls through the gap between team members.",
                "When I analyse a market, I use primary and secondary sources and label which conclusions come from which source.",
                "I can create a clear presentation slide that communicates one insight in under thirty seconds without the speaker's notes.",
                "I organise my business analysis so a colleague could pick it up and continue it accurately without a lengthy handover conversation.",
            ],
        },
        "ru": {
            "logic": [
                "Перед рекомендацией стратегии я определяю ключевое допущение и что должно оказаться верным, чтобы она провалилась.",
                "Когда бизнес-метрика падает, я разделяю внешние факторы (неуправляемые) и внутренние до принятия решения.",
                "Для сложных решений я строю дерево решений, намечая вероятные исходы каждого варианта до вложения ресурсов.",
                "Когда масштаб проекта превышает ресурсы, я нахожу минимальную версию, которая ещё приносит ключевую ценность.",
                "Перед предложением нового инициативы я проверяю, можно ли небольшим изменением использовать существующий процесс.",
            ],
            "data": [
                "Перед деловой рекомендацией я проверяю, что данные актуальны, релевантны и из надёжного источника.",
                "Замечая бизнес-тренд, я проверяю, статистически ли он значим или это краткосрочное колебание.",
                "Я определяю два-три ключевых показателя для цели, а не отслеживаю двадцать, теряя фокус.",
                "Когда бизнес-кейс зависит от ключевого числа, я строю диапазон — оптимистичный, реалистичный, пессимистичный.",
                "До утверждения, что наши показатели сильны или слабы, я проверяю данные конкурентов и рыночные ориентиры.",
            ],
            "creativity": [
                "Когда стандартная бизнес-модель не подходит новому рынку, я объединяю элементы из двух разных отраслей.",
                "Я генерирую три-пять различных стратегических вариантов для клиента до презентации рекомендуемого.",
                "Когда продукт теряет долю рынка, я ищу работу, на которую клиенты его нанимают, до перепроектирования.",
                "Я ищу бизнес-проблемы, которые другие считают нерешаемыми: в них часто скрываются возможности с малой конкуренцией.",
                "При ограниченных ресурсах я нахожу дешёвый способ проверить ключевое допущение стратегии до вложения полного бюджета.",
            ],
            "people": [
                "Когда нужна поддержка стейкхолдеров, я определяю главную озабоченность каждого и отвечаю на неё до полной презентации.",
                "Когда команда не согласна в приоритетах, я провожу структурированный разговор, выявляющий компромиссы, а не навязываю решение.",
                "Деловые предложения я представляю сначала с рекомендацией, потом с доказательствами, чтобы ЛПР сразу мог включиться.",
                "При задержке проекта я проактивно сообщаю обновлённые сроки и план, а не жду вопросов.",
                "Я адаптирую стиль общения под аудиторию — резюме для руководства, детализация для аналитиков — не теряя точности.",
            ],
            "technical": [
                "Я могу написать бизнес-кейс — проблема, варианты, рекомендация, финансы, риски — который руководитель прочитает за 10 минут.",
                "Я использую инструмент управления проектами для отслеживания задач, ответственных и сроков.",
                "Анализируя рынок, я использую первичные и вторичные источники и маркирую, какой вывод откуда.",
                "Я могу создать слайд презентации, передающий один инсайт за 30 секунд без заметок спикера.",
                "Я организую бизнес-анализ так, чтобы коллега мог продолжить его точно без длинного разговора о передаче.",
            ],
        },
        "uz": {
            "logic": [
                "Biznes strategiyasini tavsiya qilishdan oldin u bog'liq bo'lgan asosiy farazni va uning muvaffaqiyatsizligi uchun nima to'g'ri bo'lishi kerakligini aniqlayman.",
                "Biznes ko'rsatkichi pasayganda, nima o'zgartirish kerakligini hal qilishdan oldin boshqara olmaydigan tashqi omillarni boshqara oladigan ichki omillardan ajrataman.",
                "Yuqori stavkali tanlovlar uchun resurslarni sarflashdan oldin har bir variant ehtimoliy natijalarini xaritalashtirib qaror daraxti quraman.",
                "Loyiha ko'lami mavjud resurslarga qaraganda katta bo'lsa, hali asosiy qiymatni yetkazib beradigan minimal versiyani aniqlayman.",
                "Yangi tashabbus taklif qilishdan oldin kichik o'zgarish bilan mavjud jarayon, jamoa yoki vosita ishni bajara oladimi deb tekshiraman.",
            ],
            "data": [
                "Biznes tavsiyasini taqdim etishdan oldin ma'lumotlarimning so'nggi, tegishli va ishonchli manbadan ekanligini tekshiraman.",
                "Biznes tendensiyasini ko'rganda, xulosalar chiqarishdan oldin u statistik jihatdan muhimmi yoki qisqa muddatli o'zgarishmi deb tekshiraman.",
                "Yigirmatasini kuzatib, diqqatni yo'qotish o'rniga maqsad uchun eng muhim ikki-uch ko'rsatkichni belgilayman.",
                "Biznes ishi asosiy raqamga bog'liq bo'lsa, bitta raqam taqdim etish o'rniga — optimistik, realistik, pessimistik — diapazon quraman.",
                "Biznes samaramiz kuchli yoki zaifligini ta'riflashdan oldin raqobatchi ma'lumotlari va bozor me'yorlarini tekshiraman.",
            ],
            "creativity": [
                "Standart biznes modeli yangi bozorga mos kelmasa, yangi narsa taklif qilish uchun ikkita turli sanoat elementlarini birlashtiram.",
                "Mijoz uchun tavsiya etilganini taqdim etishdan oldin uchdan beshgacha turli strategik variantlar yarataman.",
                "Mahsulot bozor ulushini yo'qotayotganda, uni qayta loyihalashtirish oldidan mijozlar uni bajarishga yollayotgan ishni qidiraman.",
                "Boshqalar hal qilib bo'lmaydigan deb rad etgan biznes muammolarini qidiraman, chunki ularda ko'pincha cheklangan raqobatli imkoniyatlar yashiringan.",
                "Resurslar cheklangan bo'lganda, to'liq byudjetni sarflashdan avval strategiyaning asosiy farazini arzon tekshirish yo'lini topaman.",
            ],
            "people": [
                "Qaror uchun manfaatdor tomonlar qo'llab-quvvatlashi kerak bo'lganda, to'liq taklifni taqdim etishdan oldin har bir kishining asosiy tashvishini aniqlab, unga javob beraman.",
                "Jamoa ustuvorliklar bo'yicha kelisha olmasa, qaror yuklamasdan savdo-sotiqni ochib beradigan tuzilgan suhbatni tashkil qilaman.",
                "Biznes takliflarini birinchi tavsiya, keyin qo'llab-quvvatlovchi dalillar bilan taqdim etamanki, qaror qabul qiluvchi darhol jalb bo'lsin.",
                "Loyiha kechiktirilganda, so'ralishini kutmasdan yangilangan muddatlar va qayta ko'rib chiqilgan rejani proaktiv ravishda yetkazaman.",
                "Aniqlikni yo'qotmasdan muloqot uslubimni auditoriyaga moslashtiram — rahbarlar uchun ijroiya xulosasi, tahlilchilar uchun batafsil tavsif.",
            ],
            "technical": [
                "Katta rahbar o'n daqiqada ko'rib chiqishi mumkin bo'lgan biznes ishi hujjatini — muammo, variantlar, tavsiya, moliya, xatarlar — yoza olaman.",
                "Jamoachlar o'rtasida hech narsa tushib qolmasligi uchun vazifalar, mas'ullar va muddatlarni kuzatish uchun loyihani boshqarish vositasidan foydalanaman.",
                "Bozorni tahlil qilganda, birlamchi va ikkilamchi manbalardan foydalanaman va qaysi xulosa qayerdan ekanligini belgilayman.",
                "Bir tushunchani ma'ruzachi eslatmalarisiz o'ttiz soniya ichida yetkazadigan aniq taqdimot slaydini yarata olaman.",
                "Biznes tahlilimni shunday tartiblamanki, hamkasb uzun topshirish suhbatisiz uni aniq davom ettira olsin.",
            ],
        },
    },
}

# Generic fallback templates (used for interests without specific questions)
_GENERIC: dict = {
    "en": {
        "logic": [
            "When I face a problem I have not seen before, I break it into smaller parts before looking for a solution.",
            "I compare at least two different approaches before choosing how to tackle a new challenge.",
            "I check whether my solution works for edge cases before calling a task complete.",
            "When something does not go as planned, I trace back through each step to find where it went wrong.",
            "I document my reasoning when I make a decision so I or others can review it later.",
        ],
        "data": [
            "Before making an important decision, I look for evidence or data rather than relying on intuition alone.",
            "I define what success looks like — in measurable terms — before starting a significant piece of work.",
            "When I get unexpected results, I check whether the input data was correct before changing my method.",
            "I track progress over time with numbers or records rather than relying on memory.",
            "I compare results before and after a change to understand whether it actually made things better.",
        ],
        "creativity": [
            "When the obvious approach does not work, I deliberately try something different rather than repeating it.",
            "I enjoy experimenting with new methods or tools even when a familiar one would be sufficient.",
            "When I present an idea, I include at least one alternative so the audience can compare options.",
            "I look outside my field for inspiration when I am stuck on a problem.",
            "I try to simplify complex things into a clear story or diagram that someone unfamiliar could understand.",
        ],
        "people": [
            "When someone gives me feedback, I listen fully and ask one clarifying question before responding.",
            "I check in with colleagues or users during a project rather than waiting until the end to share my work.",
            "When I explain a complex topic, I adjust the level of detail based on what the other person already knows.",
            "I acknowledge mistakes openly and explain what I will do differently rather than hoping they go unnoticed.",
            "I make sure the people affected by my work understand how it will change their situation before it launches.",
        ],
        "technical": [
            "I practice a new skill by applying it to a real small task rather than only reading about it.",
            "I maintain organised records or files so I can find work from months ago without searching extensively.",
            "When a tool or workflow breaks, I try to fix it myself first and document what I tried before asking for help.",
            "I test my output against the original requirement before marking a task as finished.",
            "I keep my tools and environment updated and understand why each tool is in my workflow.",
        ],
    },
    "ru": {
        "logic": [
            "Встречая незнакомую задачу, я разбиваю её на части до начала поиска решения.",
            "Перед выбором подхода я сравниваю минимум два варианта решения.",
            "Я проверяю, работает ли решение в крайних случаях, до завершения задачи.",
            "Когда что-то идёт не по плану, я прохожу через каждый шаг, чтобы найти причину.",
            "Я документирую своё мышление при принятии решений, чтобы можно было проверить позже.",
        ],
        "data": [
            "Перед важным решением я ищу факты, а не полагаюсь только на интуицию.",
            "Я определяю, как выглядит успех в измеримых показателях, до начала серьёзной работы.",
            "Получив неожиданный результат, я сначала проверяю входные данные, а не меняю метод.",
            "Я отслеживаю прогресс в числах, а не в памяти.",
            "Я сравниваю результаты до и после изменения, чтобы понять, действительно ли стало лучше.",
        ],
        "creativity": [
            "Если очевидный подход не работает, я намеренно пробую другой, а не повторяю то же самое.",
            "Я с удовольствием экспериментирую с новыми методами, даже когда можно обойтись привычным.",
            "Предлагая идею, я включаю хотя бы одну альтернативу для сравнения.",
            "Я ищу вдохновение вне своей области, когда застреваю на проблеме.",
            "Я стараюсь упростить сложные вещи до понятного рассказа или схемы.",
        ],
        "people": [
            "Получая обратную связь, я слушаю полностью и задаю один уточняющий вопрос до ответа.",
            "Я сверяюсь с коллегами или пользователями в ходе проекта, а не жду финала.",
            "Объясняя сложную тему, я подстраиваю уровень детализации под знания собеседника.",
            "Я открыто признаю ошибки и объясняю, что сделаю иначе.",
            "Я убеждаюсь, что люди, на которых влияет моя работа, понимают изменения до их запуска.",
        ],
        "technical": [
            "Новый навык я отрабатываю на реальной небольшой задаче, а не только читаю о нём.",
            "Я веду организованные записи, чтобы найти работу месячной давности без длительного поиска.",
            "Когда инструмент ломается, я сначала пробую исправить сам и документирую попытки.",
            "Я проверяю результат по исходному требованию перед тем, как считать задачу выполненной.",
            "Я обновляю инструменты и понимаю, зачем каждый из них в моём рабочем процессе.",
        ],
    },
    "uz": {
        "logic": [
            "Notanish muammoga duch kelganimda, yechim izlashdan oldin uni kichik qismlarga ajrataman.",
            "Yondashuv tanlashdan oldin kamida ikkita variantni solishtiram.",
            "Vazifani bajarilgan deb belgilashdan oldin, yechim chegaraviy holatlarda ham ishlashini tekshiraman.",
            "Narsa rejadagidek bormasa, nima xato ketganini topish uchun har bir qadamni kuzataman.",
            "Qarorni qabul qilganimda mulohazamni hujjatlashtiraman, keyinroq tekshirish mumkin bo'lsin.",
        ],
        "data": [
            "Muhim qaror qilishdan oldin faqat intuitsiяga tayanib emas, dalil yoki ma'lumot qidiraman.",
            "Jiddiy ish boshlashdan oldin muvaffaqiyat qanday ko'rinishini o'lchanuvchi ko'rsatkichlarda aniqlayman.",
            "Kutilmagan natija olsam, metodimni o'zgartirishdan oldin kiruvchi ma'lumotlar to'g'riligini tekshiraman.",
            "Progressni xotirada emas, raqamlar yoki yozuvlar bilan kuzataman.",
            "O'zgarish haqiqatan yaxshilagan-yaxshilamaganini tushunish uchun oldin va keyin natijalarni solishtiram.",
        ],
        "creativity": [
            "Aniq yondashuv ishlamasa, uni takrorlash o'rniga ataylab boshqa narsani sinab ko'raman.",
            "Tanish yondashuv yetarli bo'lsa ham, yangi usullar yoki asboblarni sinab ko'rishni yoqtiraman.",
            "G'oyani taqdim etganimda, auditoriya solishtira olishi uchun kamida bitta muqobilni qo'shaman.",
            "Muammoga qotib qolsam, o'z sohamdan tashqarida ilhom qidiraman.",
            "Murakkab narsalarni tanish bo'lmagan kishi tushuna oladigan aniq hikoya yoki diagrammaga soddalashtiraman.",
        ],
        "people": [
            "Kimdir fikr-mulohaza berganda, javob berishdan oldin to'liq tinglab, bitta aniqlashtiruvchi savol beraman.",
            "Loyiha davomida hamkasb yoki foydalanuvchilar bilan tekshiraman, oxirigacha kutmayman.",
            "Murakkab mavzuni tushuntirganda, tafsilot darajasini suhbatdoshning bilimlari asosida moslashtiraman.",
            "Xatolarni ochiq tan olib, nima boshqacha qilishimni tushuntiraman.",
            "Ishim ta'sir qiladigan odamlar ishga tushishidan oldin o'zgarishlarni tushunishiga ishonch hosil qilaman.",
        ],
        "technical": [
            "Yangi ko'nikmani faqat o'qish emas, real kichik vazifada qo'llab mashq qilaman.",
            "Oylar avvalgi ishni uzoq qidirmasdan topish uchun tartibli yozuv va fayllarni saqlayman.",
            "Asbob yoki ish jarayoni buzilganda, avval o'zim tuzatishga urinaman va sinashlarni hujjatlashtiraman.",
            "Natijani bajarilgan deb belgilashdan oldin dastlabki talabga nisbatan tekshiraman.",
            "Asboblarni yangilab boraman va har biri nima uchun ish jarayonimda ekanini tushunaman.",
        ],
    },
}


def build_fallback_questions(request: GenerateQuestionsRequest) -> list:
    """Build 25 behavioral questions without an AI call."""
    language = request.language
    interests = request.interests
    dimensions = ["logic", "data", "creativity", "people", "technical"]
    questions = []
    for idx in range(25):
        interest = interests[idx % len(interests)]
        dimension = dimensions[idx % len(dimensions)]
        template_idx = (idx // len(dimensions)) % 5
        domain = _QUESTIONS.get(interest) or _GENERIC
        domain_lang = domain.get(language) or domain.get("en") or {}
        templates = domain_lang.get(dimension) or _GENERIC.get(language, _GENERIC["en"])[dimension]
        text = templates[template_idx % len(templates)]
        questions.append(
            GeneratedQuestion(
                id=idx + 1,
                text=text,
                category=dimension,
                interest=interest,
            )
        )
    return questions
